name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:        
    - uses: actions/checkout@v1
      
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Gradle for Windows
      run: ./gradlew distZip
      if: startsWith(runner.os, 'Windows')
      
    - name: Build with Gradle for Linux/Mac
      run: ./gradlew distTar
      if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
      
    - uses: actions/upload-artifact@master
      with: 
        name: build-${{ matrix.os }}
        path: build/distributions/

    - name: Publish
      run: ./gradlew publish
      env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
